#!/bin/bash

ENCODER='none'

DATA1='cnsm_exp1'
DATA2='cnsm_exp2_1'
DATA3='cnsm_exp2_2'

BATCH_SIZE=64
DIM_LSTM_HIDDEN=-1
LR=0.001
OPTIMIZER='Adam'
REDUCE1='max'
REDUCE2='mean'
NHEAD=-1
DIM_FEEDFORWARD=-1

./ad_run.sh 6 $ENCODER $DATA1 $BATCH_SIZE $DIM_LSTM_HIDDEN $LR $OPTIMIZER $REDUCE2 $NHEAD $DIM_FEEDFORWARD 1>/dev/null 2>&1 &
./ad_run.sh 6 $ENCODER $DATA2 $BATCH_SIZE $DIM_LSTM_HIDDEN $LR $OPTIMIZER $REDUCE2 $NHEAD $DIM_FEEDFORWARD 1>/dev/null 2>&1 &
./ad_run.sh 7 $ENCODER $DATA3 $BATCH_SIZE $DIM_LSTM_HIDDEN $LR $OPTIMIZER $REDUCE1 $NHEAD $DIM_FEEDFORWARD 1>/dev/null 2>&1 &

